
package connection.webservices.consumer.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmartHomeManagerWebServiceDescriptorService", targetNamespace = "http://wsprovider.connection.global.smarthome.thm.de/", wsdlLocation = "http://localhost:8080/services?wsdl")
public class SmartHomeManagerWebServiceDescriptorService
    extends Service
{

    private final static URL SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_EXCEPTION;
    private final static QName SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_QNAME = new QName("http://wsprovider.connection.global.smarthome.thm.de/", "SmartHomeManagerWebServiceDescriptorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_WSDL_LOCATION = url;
        SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_EXCEPTION = e;
    }

    public SmartHomeManagerWebServiceDescriptorService() {
        super(__getWsdlLocation(), SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_QNAME);
    }

    public SmartHomeManagerWebServiceDescriptorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_QNAME, features);
    }

    public SmartHomeManagerWebServiceDescriptorService(URL wsdlLocation) {
        super(wsdlLocation, SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_QNAME);
    }

    public SmartHomeManagerWebServiceDescriptorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_QNAME, features);
    }

    public SmartHomeManagerWebServiceDescriptorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmartHomeManagerWebServiceDescriptorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmartHomeManagerWebServices
     */
    @WebEndpoint(name = "SmartHomeManagerWebServicesPort")
    public SmartHomeManagerWebServices getSmartHomeManagerWebServicesPort() {
        return super.getPort(new QName("http://wsprovider.connection.global.smarthome.thm.de/", "SmartHomeManagerWebServicesPort"), SmartHomeManagerWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmartHomeManagerWebServices
     */
    @WebEndpoint(name = "SmartHomeManagerWebServicesPort")
    public SmartHomeManagerWebServices getSmartHomeManagerWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsprovider.connection.global.smarthome.thm.de/", "SmartHomeManagerWebServicesPort"), SmartHomeManagerWebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_EXCEPTION!= null) {
            throw SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_EXCEPTION;
        }
        return SMARTHOMEMANAGERWEBSERVICEDESCRIPTORSERVICE_WSDL_LOCATION;
    }

}
