
package connection.webservices.consumer.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmartHomeManagerWebServices", targetNamespace = "http://wsprovider.connection.global.smarthome.thm.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmartHomeManagerWebServices {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/loginRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/loginResponse")
    public CommandResponseObject login(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        UserTransferObject arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/logoutRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/logoutResponse")
    public CommandResponseObject logout(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        UserTransferObject arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/setHeatingTemperatureRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/setHeatingTemperatureResponse")
    public CommandResponseObject setHeatingTemperature(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getHeatingTemperatureRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getHeatingTemperatureResponse")
    public double getHeatingTemperature(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getShutterPositionRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getShutterPositionResponse")
    public String getShutterPosition(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.ShutterTransferObjectArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getAllShutterDataRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getAllShutterDataResponse")
    public ShutterTransferObjectArray getAllShutterData(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createWeatherStationRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createWeatherStationResponse")
    public CommandResponseObject createWeatherStation(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        WeatherStationTransferObject arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteWeatherStationRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteWeatherStationResponse")
    public CommandResponseObject deleteWeatherStation(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getOutdoorTemperatureRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getOutdoorTemperatureResponse")
    public double getOutdoorTemperature(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getRainfallAmountRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getRainfallAmountResponse")
    public double getRainfallAmount(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.WeatherStationTransferObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getWeatherStationDataRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getWeatherStationDataResponse")
    public WeatherStationTransferObject getWeatherStationData(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createThermometerRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createThermometerResponse")
    public CommandResponseObject createThermometer(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ThermometerTransferObject arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteThermometerRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteThermometerResponse")
    public CommandResponseObject deleteThermometer(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getIndoorTemperatureRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getIndoorTemperatureResponse")
    public double getIndoorTemperature(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.ThermometerTransferObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getThermometerDataRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getThermometerDataResponse")
    public ThermometerTransferObject getThermometerData(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getServerInfoRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getServerInfoResponse")
    public String getServerInfo();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createHeatingRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createHeatingResponse")
    public CommandResponseObject createHeating(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        HeatingTransferObject arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteHeatingRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteHeatingResponse")
    public CommandResponseObject deleteHeating(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/switchHeatingOnRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/switchHeatingOnResponse")
    public CommandResponseObject switchHeatingOn(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/switchHeatingOffRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/switchHeatingOffResponse")
    public CommandResponseObject switchHeatingOff(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.HeatingTransferObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getHeatingDataRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getHeatingDataResponse")
    public HeatingTransferObject getHeatingData(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createShutterRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createShutterResponse")
    public CommandResponseObject createShutter(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ShutterTransferObject arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteShutterRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteShutterResponse")
    public CommandResponseObject deleteShutter(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ShutterTransferObject arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/moveShuttersUpRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/moveShuttersUpResponse")
    public CommandResponseObject moveShuttersUp(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/moveShuttersDownRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/moveShuttersDownResponse")
    public CommandResponseObject moveShuttersDown(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.ShutterTransferObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getShutterDataRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getShutterDataResponse")
    public ShutterTransferObject getShutterData(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ShutterTransferObject arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createUserRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/createUserResponse")
    public CommandResponseObject createUser(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        UserTransferObject arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteUserRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/deleteUserResponse")
    public CommandResponseObject deleteUser(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        UserTransferObject arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/alterUserRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/alterUserResponse")
    public CommandResponseObject alterUser(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        UserTransferObject arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.UserTransferObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getUserDataRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getUserDataResponse")
    public UserTransferObject getUserData(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        UserTransferObject arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.UserTransferObjectArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getAllUserDataRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getAllUserDataResponse")
    public UserTransferObjectArray getAllUserData(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getAirHumidityRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getAirHumidityResponse")
    public double getAirHumidity(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getAirPressureRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getAirPressureResponse")
    public double getAirPressure(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getWindVelocityRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/getWindVelocityResponse")
    public double getWindVelocity(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0);

    /**
     * 
     * @return
     *     returns connection.webservices.consumer.stubs.CommandResponseObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/undoLastCommandRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/undoLastCommandResponse")
    public CommandResponseObject undoLastCommand();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns connection.webservices.consumer.stubs.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/readLogsRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/readLogsResponse")
    public StringArray readLogs(
        @WebParam(name = "arg0", partName = "arg0")
        UserTransferObject arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param weight
     * @param height
     * @return
     *     returns double
     */
    @WebMethod(operationName = "body-mass-index")
    @WebResult(name = "your-bmi", partName = "your-bmi")
    @Action(input = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/body-mass-indexRequest", output = "http://wsprovider.connection.global.smarthome.thm.de/SmartHomeManagerWebServices/body-mass-indexResponse")
    public double bodyMassIndex(
        @WebParam(name = "height", partName = "height")
        double height,
        @WebParam(name = "weight", partName = "weight")
        double weight);

}
